### PR TITLE
Fix export in typescript with namespace

### PR DESCRIPTION
**Pull request by rmcmk**

### CODE REVIEW

**Comment by tigercosmos** [comment]
@rmcmk  could you explain the PR?

**Comment by rmcmk** [comment]
@tigercosmos When using [node-color-log](https://github.com/tigercosmos/node-color-log) with a typescript module (in my case) and have both `use export =` and `export` in the same module, you will receive the following error:

    TS2309: An export assignment cannot be used in a module with other exported elements.

However, if you declare a declare a namespace with the same name as the variable used in the `exports = expression`, you can place types inside of that namespace, making them accessible to consuming modules, which is what this PR accomplishes. Improves further compatibility. Should not break other environments.

**Comment by rmcmk** [comment]
@tigercosmos When using [node-color-log](https://github.com/tigercosmos/node-color-log) with a typescript module (in my case) and have both use export = and export in the same module, you receive the following error:

TS2309: An export assignment cannot be used in a module with other exported elements.

However, if you declare a declare a namespace for the internal `exports`, you can place types inside of that namespace, making them accessible to consuming modules, which is what this PR accomplishes. Improves further compatibility. Should not break other environments.

**Comment by tigercosmos** [comment]
@rmcmk  LGTM thanks

**Comment by tigercosmos** [comment]
10.0.2

**Comment by bugron** [comment]
Hi @rmcmk @tigercosmos. Quick question. How do I use the `COLOR` type after this change? Shouldn't the `types` namespace be exported too? Thanks.

**Pull request merged**
